# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICjdD_H75S9t3lmhFxdB0BfY6wAtO8za

#Mi primer proyecto
##Samuel Bnaguero Balanta - sbanguerob@estudiante.uniajc.edu.co
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor



df = pd.read_csv('mental_health_spain_final.csv')
df.head()

df.shape

df.hist(figsize=(15,15))

df['anxiety_diff'].describe()

df['anxiety_diff'].value_counts()

"""#chequeo de fuga de datos"""

df[['anxiety', 'anxiety_diff']].corr()

df['anxiety_diff'].hist(bins=30, figsize=(6, 4))

"""#Modelo ML

1. seleccionar variables independientes y dependientes
"""

y = df['anxiety']
#X = df[['anxiety', 'depression', 'online_therapy', 'panic_attacks', 'stress', 'online_diff']]
#X = df[['panic_attacks', 'online_diff', 'stress']]
X = df[['stress', 'panic_attacks', 'depression']]

"""# 2. particion de los datos

"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.7, random_state=42)

"""#3. entrenamiento de los modelos ML

3.1. Adaboots
"""

modelo1 = AdaBoostClassifier(n_estimators=100, random_state=0, learning_rate = 1.0 )
modelo1.fit(X_train, y_train)

y_pred = modelo1.predict(X_test)

"""#3.2 svm"""

modelo2 = svm.SVC(decision_function_shape='ovo', C=10, kernel='rbf',
                   gamma='scale', degree=3, probability=True, random_state=42)
modelo2.fit(X_train, y_train)

y_pred2 = modelo2.predict(X_test)

"""#4. Metricas diagnosticas"""

print(classification_report(y_test, y_pred))

print(classification_report(y_test, y_pred2))

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Matriz de correlacion completa')
plt.tight_layout()
plt.show()

"""curva roc"""

# --- ROC Curve for AdaBoost (modelo1) ---
# Get the classes from the trained AdaBoost model
ada_classes = modelo1.classes_

# Binarize y_test using the classes from the AdaBoost model
# This ensures consistency between y_test_binarized and y_proba1
y_test_binarized_ada = label_binarize(y_test, classes=ada_classes)

# Get predicted probabilities for AdaBoost
y_proba1 = modelo1.predict_proba(X_test)

# Compute micro-average ROC curve and ROC area for AdaBoost
fpr_micro1, tpr_micro1, _ = roc_curve(y_test_binarized_ada.ravel(), y_proba1.ravel())
roc_auc_micro1 = auc(fpr_micro1, tpr_micro1)

# Plot the ROC curve for AdaBoost
plt.figure(figsize=(8, 6))
plt.plot(fpr_micro1, tpr_micro1, label=f'AdaBoost (Micro-average AUC = {roc_auc_micro1:.2f})', color='darkorange', linestyle='-', linewidth=2)
plt.plot([0, 1], [0, 1], 'k--', label='Chance (AUC = 0.50)') # Removed redundant color='navy'
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - AdaBoost (Micro-average)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# --- ROC Curve for SVM (modelo2) ---
# Get the classes from the trained SVM model
svm_classes = modelo2.classes_

# Binarize y_test using the classes from the SVM model
y_test_binarized_svm = label_binarize(y_test, classes=svm_classes)

# Get predicted probabilities for SVM
y_proba2 = modelo2.predict_proba(X_test)

# Compute micro-average ROC curve and ROC area for SVM
fpr_micro2, tpr_micro2, _ = roc_curve(y_test_binarized_svm.ravel(), y_proba2.ravel())
roc_auc_micro2 = auc(fpr_micro2, tpr_micro2)

# Plot the ROC curve for SVM
plt.figure(figsize=(8, 6))
plt.plot(fpr_micro2, tpr_micro2, label=f'SVM (Micro-average AUC = {roc_auc_micro2:.2f})', color='green', linestyle='-', linewidth=2)
plt.plot([0, 1], [0, 1], 'k--', label='Chance (AUC = 0.50)') # Removed redundant color='navy'
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - SVM (Micro-average)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()



# Get feature importances from modelo1 (AdaBoost)
feature_importances = modelo1.feature_importances_

# Get feature names from the original DataFrame X
feature_names = X.columns

# Create a Series for better visualization
importance_df = pd.Series(feature_importances, index=feature_names)

# Sort the features by importance
importance_df = importance_df.sort_values(ascending=False)

# Plot the feature importances
plt.figure(figsize=(10, 6))
importance_df.plot(kind='bar')
plt.title('Feature Importances - AdaBoost Classifier')
plt.xlabel('Features')
plt.ylabel('Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""#modelos de regresion"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""#regresion lineal"""

from sklearn.metrics import mean_absolute_percentage_error

modelo_lr = LinearRegression()

modelo_lr.fit(X_train_scaled, y_train)

y_pred_lr = modelo_lr.predict(X_test_scaled)

print("R2:", r2_score(y_test, y_pred_lr))
print("MAE:", mean_absolute_error(y_test, y_pred_lr))
print("MSE:", mean_squared_error(y_test, y_pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))
print("MAPE:", mean_absolute_percentage_error(y_test, y_pred_lr))

"""#Random Forest"""

modelo_rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    random_state=42
)

modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)

print("R2:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

"""# gradiente Boosting"""

modelo_gb = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

modelo_gb.fit(X_train, y_train)

y_pred_gb = modelo_gb.predict(X_test)

print("R2:", r2_score(y_test, y_pred_gb))
print("MAE:", mean_absolute_error(y_test, y_pred_gb))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_gb)))

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

print("ROC curves are typically used for classification models, not regression models.")
print("For regression models, you can visualize their performance using scatter plots of actual vs. predicted values, or residual plots.")
print("You have already calculated relevant metrics like R2, MAE, MSE, and RMSE for your regression models.")

# Re-defining df and X, y (assuming 'mental_health_spain_final.csv' is available)
df = pd.read_csv('mental_health_spain_final.csv')
y = df['anxiety']
X = df[['stress', 'panic_attacks', 'depression']]

# Re-splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

# Re-scaling data for Linear Regression
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Re-training Linear Regression model and getting predictions
modelo_lr = LinearRegression()
modelo_lr.fit(X_train_scaled, y_train)
y_pred_lr = modelo_lr.predict(X_test_scaled)

# Re-training Random Forest Regressor model and getting predictions
modelo_rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    random_state=42
)
modelo_rf.fit(X_train, y_train)
y_pred_rf = modelo_rf.predict(X_test)

# Re-training Gradient Boosting Regressor model and getting predictions
modelo_gb = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)
modelo_gb.fit(X_train, y_train)
y_pred_gb = modelo_gb.predict(X_test)

# Example of a scatter plot for Linear Regression predictions
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_lr, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values (Linear Regression)')
plt.title('Actual vs. Predicted Values (Linear Regression)')
plt.grid(True)
plt.show()

# Example of a scatter plot for Random Forest Regression predictions
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_rf, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values (Random Forest)')
plt.title('Actual vs. Predicted Values (Random Forest)')
plt.grid(True)
plt.show()

# Example of a scatter plot for Gradient Boosting Regression predictions
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_gb, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values (Gradient Boosting)')
plt.title('Actual vs. Predicted Values (Gradient Boosting)')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Get feature importances from modelo_rf (Random Forest Regressor)
feature_importances_rf = modelo_rf.feature_importances_

# Get feature names from the original DataFrame X
feature_names_rf = X.columns

# Create a Series for better visualization
importance_df_rf = pd.Series(feature_importances_rf, index=feature_names_rf)

# Sort the features by importance
importance_df_rf = importance_df_rf.sort_values(ascending=False)

# Plot the feature importances
plt.figure(figsize=(10, 6))
importance_df_rf.plot(kind='bar')
plt.title('Feature Importances - Random Forest Regressor')
plt.xlabel('Features')
plt.ylabel('Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Feature Importances for Random Forest Regressor:")
print(importance_df_rf)

"""---"""

# Para la matriz de correlación
plt.figure(figsize=(8, 6))
sns.heatmap(df[['anxiety', 'stress', 'panic_attacks', 'depression', 'online_therapy']].corr(), annot=True, cmap='coolwarm')
plt.title('Matriz de Correlación de Pearson')
plt.savefig('matriz_correlacion.png', dpi=300, bbox_inches='tight')
plt.show()

# Para el scatter de Random Forest
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_rf, alpha=0.6, color='blue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel('Valores Reales')
plt.ylabel('Valores Predichos (Random Forest)')
plt.savefig('real_vs_predicho_rf.png', dpi=300, bbox_inches='tight')
plt.show()

# Para la importancia de variables del Random Forest Regressor
importancia = modelo_rf.feature_importances_
features = ['stress', 'panic_attacks', 'depression'] # Ajusta según el orden de tus columnas X
plt.figure(figsize=(8, 5))
sns.barplot(x=importancia, y=features, palette='viridis')
plt.xlabel('Importancia Relativa')
plt.title('Importancia de Variables - Random Forest Regressor')
plt.savefig('importancia_variables.png', dpi=300, bbox_inches='tight')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Cargar el dataset
df = pd.read_csv('mental_health_spain_final.csv')

# 2. Seleccionar estrictamente la variable objetivo y las predictoras elegidas
# Se excluyen las variables con fuga de datos (data leakage) y las irrelevantes
variables_regresion = ['anxiety', 'stress', 'panic_attacks', 'depression']
df_filtrado = df[variables_regresion]

# 3. Calcular la matriz de correlación paramétrica de Pearson
matriz_corr = df_filtrado.corr(method='pearson')

# 4. Configurar el lienzo de la gráfica (Estándar de publicación científica)
plt.figure(figsize=(7, 5.5))

# Definir un mapa de colores divergente y estético (coolwarm o RdBu_r)
sns.heatmap(
    matriz_corr,
    annot=True,          # Mostrar los valores numéricos (r) dentro de cada celda
    fmt=".3f",           # Tres decimales para precisión de ingeniería
    cmap="coolwarm",     # Escala térmica: rojo (positivo), azul (negativo)
    vmin=-1, vmax=1,     # Límites teóricos del coeficiente de Pearson
    square=True,         # Forzar celdas cuadradas simétricas
    linewidths=0.5,      # Separación elegante entre celdas
    cbar_kws={"label": "Coeficiente de Correlación (r)"} # Etiqueta de la barra lateral
)

# 5. Ajustar títulos y etiquetas del sistema analítico
plt.title('Matriz de Correlación de Pearson - Variables Seleccionadas', fontsize=12, fontweight='bold', pad=15)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

# 6. Exportar la imagen en alta resolución con el nombre exacto usado en tu LaTeX
plt.savefig('matriz_correlacion.png', dpi=300, bbox_inches='tight')

# 7. Desplegar matriz en consola para verificar los datos numéricos exactos
print("Matriz de Correlación Calculada:")
print(matriz_corr)

plt.show()

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 1. Cargar el dataset y asegurar que la columna 'date' sea datetime
df = pd.read_csv('mental_health_spain_final.csv')
df['date'] = pd.to_datetime(df['date'])

# 2. Seleccionar variables independientes (X) y dependiente (y)
y = df['anxiety']
X = df[['stress', 'panic_attacks', 'depression']]

# 3. Particionar los datos manteniendo el orden temporal para el plotting
# (Aunque train_test_split no garantiza orden, para este tipo de visualización
# sobre el conjunto de prueba, es práctico usarlo y luego reordenar si es necesario)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.7, random_state=42)

# Asegurar que el DataFrame original se alinee con los índices de X_test/y_test para la fecha
df_test = df.loc[y_test.index].copy()

# 4. Re-entrenar el modelo Random Forest (ya que fue el mejor)
modelo_rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    random_state=42
)
modelo_rf.fit(X_train, y_train)

# 5. Realizar predicciones sobre el conjunto de prueba
y_pred_rf = modelo_rf.predict(X_test)

# 6. Crear un DataFrame para la visualización con fechas, valores reales y predichos
results_df = pd.DataFrame({
    'date': df_test['date'],
    'Actual Anxiety': y_test,
    'Predicted Anxiety (RF)': y_pred_rf
})

# Ordenar por fecha para una visualización correcta de series temporales
results_df = results_df.sort_values(by='date').reset_index(drop=True)

# 7. Plotear la variable real vs. la variable predicha a lo largo del tiempo
plt.figure(figsize=(14, 7))
plt.plot(results_df['date'], results_df['Actual Anxiety'], label='Actual Anxiety', marker='o', linestyle='-', markersize=4)
plt.plot(results_df['date'], results_df['Predicted Anxiety (RF)'], label='Predicted Anxiety (RF)', marker='x', linestyle='--', markersize=4)

plt.title('Actual vs. Predicted Anxiety Over Time (Random Forest Regressor)', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Anxiety Level', fontsize=12)
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# 1. Cargar el dataset y asegurar que la columna 'date' sea datetime
df = pd.read_csv('mental_health_spain_final.csv')
df['date'] = pd.to_datetime(df['date'])

# 2. Seleccionar variables independientes (X) y dependiente (y) para todo el dataset
y_full = df['anxiety']
X_full = df[['stress', 'panic_attacks', 'depression']]

# 3. Entrenar el modelo Random Forest en el conjunto completo de datos
# para obtener predicciones a lo largo de toda la serie temporal
modelo_rf_full = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    random_state=42
)
modelo_rf_full.fit(X_full, y_full)

# 4. Realizar predicciones sobre el conjunto completo de datos
y_pred_full = modelo_rf_full.predict(X_full)

# 5. Crear un DataFrame para la visualización con fechas, valores reales y predichos
results_df_full = pd.DataFrame({
    'date': df['date'],
    'Actual Anxiety': y_full,
    'Predicted Anxiety (RF)': y_pred_full
})

# Ordenar por fecha para una visualización correcta de series temporales
results_df_full = results_df_full.sort_values(by='date').reset_index(drop=True)

# 6. Plotear la variable real vs. la variable predicha a lo largo de todo el tiempo
plt.figure(figsize=(16, 8)) # Aumentar un poco el tamaño para la vista completa
plt.plot(results_df_full['date'], results_df_full['Actual Anxiety'], label='Actual Anxiety', marker='o', linestyle='-', markersize=3)
plt.plot(results_df_full['date'], results_df_full['Predicted Anxiety (RF)'], label='Predicted Anxiety (RF)', marker='x', linestyle='--', markersize=3)

plt.title('Actual vs. Predicted Anxiety Over Full Time Range (Random Forest Regressor)', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Anxiety Level', fontsize=12)
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# Re-load the dataset (to ensure df is available)
df = pd.read_csv('mental_health_spain_final.csv')

# Re-define independent (X) and dependent (y) variables
y = df['anxiety']
X = df[['stress', 'panic_attacks', 'depression']]

# Re-split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

# --- Linear Regression ---
# Scale the data for Linear Regression
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Linear Regression model and make predictions
modelo_lr = LinearRegression()
modelo_lr.fit(X_train_scaled, y_train)
y_pred_lr = modelo_lr.predict(X_test_scaled)

# --- Random Forest Regressor ---
# Train Random Forest Regressor model and make predictions
modelo_rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=10,
    random_state=42
)
modelo_rf.fit(X_train, y_train)
y_pred_rf = modelo_rf.predict(X_test)

# --- Gradient Boosting Regressor ---
# Train Gradient Boosting Regressor model and make predictions
modelo_gb = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)
modelo_gb.fit(X_train, y_train)
y_pred_gb = modelo_gb.predict(X_test)

# --- Plotting Actual vs. Predicted Values for each model on the test set ---

# Linear Regression Plot
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_lr, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values (y_test)')
plt.ylabel('Predicted Values (Linear Regression)')
plt.title('Actual vs. Predicted Values (Linear Regression - Test Set)')
plt.grid(True)
plt.show()

# Random Forest Regression Plot
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_rf, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values (y_test)')
plt.ylabel('Predicted Values (Random Forest)')
plt.title('Actual vs. Predicted Values (Random Forest - Test Set)')
plt.grid(True)
plt.show()

# Gradient Boosting Regression Plot
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_gb, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
plt.xlabel('Actual Values (y_test)')
plt.ylabel('Predicted Values (Gradient Boosting)')
plt.title('Actual vs. Predicted Values (Gradient Boosting - Test Set)')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Sort the DataFrame by date to ensure correct plotting of time series
df_sorted = df.sort_values(by='date').reset_index(drop=True)

# List of variables to plot against time
variables_to_plot = ['anxiety', 'depression', 'online_therapy', 'panic_attacks', 'stress']

# Create a plot for each variable
for var in variables_to_plot:
    plt.figure(figsize=(14, 6))
    plt.plot(df_sorted['date'], df_sorted[var], marker='o', linestyle='-', markersize=3, label=f'{var.replace("_", " ").title()}')
    plt.title(f'{var.replace("_", " ").title()} Over Time', fontsize=16)
    plt.xlabel('Date', fontsize=12)
    plt.ylabel(f'{var.replace("_", " ").title()} Level', fontsize=12)
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Sort the DataFrame by date to ensure correct plotting of time series
df_sorted = df.sort_values(by='date').reset_index(drop=True)

# List of variables to plot against time
variables_to_plot = ['anxiety', 'depression', 'online_therapy', 'panic_attacks', 'stress']

plt.figure(figsize=(16, 9)) # Adjust figure size for better readability with multiple lines

# Define a color palette for the lines
colors = sns.color_palette('tab10', len(variables_to_plot))

# Plot each variable on the same graph
for i, var in enumerate(variables_to_plot):
    plt.plot(df_sorted['date'], df_sorted[var], marker='o', linestyle='-', markersize=3,
             label=f'{var.replace("_", " ").title()}', color=colors[i])

plt.title('Evolution of Mental Health Variables Over Time', fontsize=18)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Level', fontsize=14)
plt.legend(title='Variables', fontsize=12, title_fontsize='13')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()